---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/integration
    tag: main

inputs:
  - name: deployment-state
  - name: bosh-stemcells-ci

run:
  path: bosh-stemcells-ci/tasks/light-google/destroy-skeletal.sh
