---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/light-stemcell-builder

inputs:
  - name: light-stemcell
  - name: bosh-stemcells-ci
  - name: builder-src
  - name: stemcells-index

outputs:
  - name: stemcells-index-output

run:
  path: bosh-stemcells-ci/tasks/light-google/publish-stemcell-and-checksum.sh

params:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_ENDPOINT: "https://s3.amazonaws.com"
  OUTPUT_BUCKET: ""
  META4_FOLDER_SUFFIX: ~
  S3_API_ENDPOINT: s3.amazonaws.com
