jobs:
- name: repack-gcp
  plan:
  - in_parallel:
    - get: bosh-linux-stemcell-builder
    - get: bosh-agent
    - get: stemcell
      resource: gcp-stemcell
    - get: bosh-stemcells-ci
  - task: repack-stemcell
    privileged: true
    file: bosh-stemcells-ci/pipelines/repack-pipeline/repack-stemcell-gcp.yml
- name: repack-aws
  plan:
  - in_parallel:
    - get: bosh-linux-stemcell-builder
    - get: bosh-agent
    - get: stemcell
      resource: aws-stemcell
    - get: bosh-stemcells-ci
  - task: repack-stemcell
    privileged: true
    file: bosh-stemcells-ci/pipelines/repack-pipeline/repack-stemcell-aws.yml
- name: repack-openstack-raw
  plan:
  - in_parallel:
    - get: bosh-linux-stemcell-builder
    - get: bosh-agent
    - get: stemcell
      resource: openstack-raw-stemcell
    - get: bosh-stemcells-ci
  - task: repack-stemcell
    privileged: true
    file: bosh-stemcells-ci/pipelines/repack-pipeline/repack-stemcell-openstack-raw.yml
- name: repack-openstack
  plan:
  - in_parallel:
    - get: bosh-linux-stemcell-builder
    - get: bosh-agent
    - get: stemcell
      resource: openstack-stemcell
    - get: bosh-stemcells-ci
  - task: repack-stemcell
    privileged: true
    file: bosh-stemcells-ci/pipelines/repack-pipeline/repack-stemcell-openstack.yml
- name: repack-azure
  plan:
  - in_parallel:
    - get: bosh-linux-stemcell-builder
    - get: bosh-agent
    - get: stemcell
      resource: azure-stemcell
    - get: bosh-stemcells-ci
  - task: repack-stemcell
    privileged: true
    file: bosh-stemcells-ci/pipelines/repack-pipeline/repack-stemcell-azure.yml
- name: repack-vsphere
  plan:
  - in_parallel:
    - get: bosh-linux-stemcell-builder
    - get: bosh-agent
    - get: stemcell
      resource: vsphere-stemcell
    - get: bosh-stemcells-ci
  - task: repack-stemcell
    privileged: true
    file: bosh-stemcells-ci/pipelines/repack-pipeline/repack-stemcell-vsphere.yml
- name: repack-vcloud
  plan:
  - in_parallel:
    - get: bosh-linux-stemcell-builder
    - get: bosh-agent
    - get: stemcell
      resource: vcloud-stemcell
    - get: bosh-stemcells-ci
  - task: repack-stemcell
    privileged: true
    file: bosh-stemcells-ci/pipelines/repack-pipeline/repack-stemcell-vsphere.yml
- name: repack-warden
  plan:
  - in_parallel:
    - get: bosh-linux-stemcell-builder
    - get: bosh-agent
    - get: stemcell
      resource: warden-stemcell
    - get: bosh-stemcells-ci
  - task: repack-stemcell
    privileged: true
    file: bosh-stemcells-ci/pipelines/repack-pipeline/repack-stemcell-warden.yml

resource_types:
- name: metalink-repository
  type: docker-image
  source:
    repository: dpb587/metalink-repository-resource

resources:
- name: bosh-linux-stemcell-builder
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-linux-stemcell-builder
    branch: master

- name: bosh-stemcells-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-stemcells-ci
    branch: master

- name: gcp-stemcell
  source:
    access_key_id: ((stemcell_aws_access_key))
    bucket: ((candidate_stemcell_bucket))
    regexp: google/bosh-stemcell-(.+)-google-kvm-ubuntu-xenial-go_agent.tgz
    secret_access_key: ((stemcell_aws_secret_key))
  type: s3

- name: vsphere-stemcell
  source:
    access_key_id: ((stemcell_aws_access_key))
    bucket: ((candidate_stemcell_bucket))
    regexp: vsphere/bosh-stemcell-(.+)-vsphere-esxi-ubuntu-xenial-go_agent.tgz
    secret_access_key: ((stemcell_aws_secret_key))
  type: s3

- name: vcloud-stemcell
  source:
    access_key_id: ((stemcell_aws_access_key))
    bucket: ((candidate_stemcell_bucket))
    regexp: vcloud/bosh-stemcell-(.+)-vcloud-esxi-ubuntu-xenial-go_agent.tgz
    secret_access_key: ((stemcell_aws_secret_key))
  type: s3

- name: azure-stemcell
  source:
    access_key_id: ((stemcell_aws_access_key))
    bucket: ((candidate_stemcell_bucket))
    regexp: azure/bosh-stemcell-(.+)-azure-hyperv-ubuntu-xenial-go_agent.tgz
    secret_access_key: ((stemcell_aws_secret_key))
  type: s3

- name: openstack-stemcell
  source:
    access_key_id: ((stemcell_aws_access_key))
    bucket: ((candidate_stemcell_bucket))
    regexp: openstack/bosh-stemcell-(.+)-openstack-kvm-ubuntu-xenial-go_agent.tgz
    secret_access_key: ((stemcell_aws_secret_key))
  type: s3

- name: openstack-raw-stemcell
  source:
    access_key_id: ((stemcell_aws_access_key))
    bucket: ((candidate_stemcell_bucket))
    regexp: openstack/bosh-stemcell-(.+)-openstack-kvm-ubuntu-xenial-go_agent-raw.tgz
    secret_access_key: ((stemcell_aws_secret_key))
  type: s3

- name: aws-stemcell
  source:
    access_key_id: ((stemcell_aws_access_key))
    bucket: ((candidate_stemcell_bucket))
    regexp: aws/bosh-stemcell-(.+)-aws-xen-hvm-ubuntu-xenial-go_agent.tgz
    secret_access_key: ((stemcell_aws_secret_key))
  type: s3

- name: warden-stemcell
  source:
    access_key_id: ((stemcell_aws_access_key))
    bucket: ((candidate_stemcell_bucket))
    regexp: warden/bosh-stemcell-(.+)-warden-boshlite-ubuntu-xenial-go_agent.tgz
    secret_access_key: ((stemcell_aws_secret_key))
  type: s3

# - name: aws-stemcell
- name: bosh-agent
  type: metalink-repository
  source:
    uri: git+https://github.com/cloudfoundry/bosh-agent-index.git
    version: '*'

