---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/main

inputs:
- name: open-vm-tools
- name: bosh-linux-stemcell-builder
- name: bosh-stemcells-ci

outputs:
- name: bosh-linux-stemcell-builder
  path: bosh-linux-stemcell-builder-out

run:
  path: bosh-stemcells-ci/tasks/bump-open-vm-tools.sh
