platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/os-image-stemcell-builder
    tag: "((image_os_tag))"

inputs:
  - name: bosh-linux-stemcell-builder
  - name: bosh-stemcells-ci
  - name: usn-log-in

run:
  path: bosh-stemcells-ci/tasks/check-usn-packages.sh
