platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-builder
    tag: "((image_os_tag))"

inputs:
  - name: bosh-linux-stemcell-builder
  - name: bosh-stemcells-ci
  - name: usn-log
  - name: usns
  - name: usn-gh-json

outputs:
  - name: updated-usn-log

run:
  path: bosh-stemcells-ci/tasks/check-if-usns-are-applicable.sh

params:
  OS:
  ESM_TOKEN:
