platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/integration
    tag: main

params:
  TOKEN: ~
  COLUMN_ID: ~
  BRANCH: ~
  DESCRIPTION: ~

inputs:
  - name: bosh-stemcells-ci

run:
  path: bosh-stemcells-ci/tasks/create-github-story.sh
