platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/main-base

params:
  TOKEN: ~
  COLUMN_ID: ~
  BRANCH: ~
  DESCRIPTION: ~

inputs:
  - name: bosh-stemcells-ci

run:
  path: bosh-stemcells-ci/tasks/create-github-story.sh
