---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-builder
    tag: "((image_os_tag))"

inputs:
  - name: bosh-stemcells-ci
  - name: sbom

outputs:

run:
  path: bosh-stemcells-ci/tasks/cve-scan.sh