platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/bosh-ecosystem-concourse

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  BRANCH:
  BUCKET:
  DESCRIPTION:
  PROJECT_ID:
  TOKEN:

inputs:
  - name: stemcells-index
  - name: bosh-stemcells-ci

run:
  path: bosh-stemcells-ci/tasks/periodic-create-story.sh
