---
platform: linux

image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: bosh-linux-stemcell-builder
  - name: bosh-stemcells-ci
  - name: director-state
  - name: bosh-cli

run:
  path: bosh-stemcells-ci/tasks/teardown.sh
