---
platform: linux

image_resource:
  type: docker-image
  source: {repository: bosh/integration, tag: main}

inputs:
  - name: bosh-linux-stemcell-builder
  - name: bosh-stemcells-ci
  - name: director-state

run:
  path: bosh-stemcells-ci/tasks/teardown.sh
