---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/main-ruby-go
    tag: "((image_os_tag))"

inputs:
  - name: bosh-linux-stemcell-builder
  - name: bosh-stemcells-ci
  - name: os-image-tarball

run:
  path: bosh-stemcells-ci/tasks/test-unit.sh
