---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/integration
    tag: main

inputs:
  - name: bosh-linux-stemcell-builder
  - name: bosh-stemcells-ci
  - name: os-image-tarball

run:
  path: bosh-stemcells-ci/tasks/test-unit.sh
