---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: bosh/integration

inputs:
- name: usn
  optional: true

outputs:
- name: message

params:
  MESSAGE_PREFIX: ~

run:
  path: /bin/bash
  args:
  - -c
  - |
    echo -n "${MESSAGE_PREFIX}" > message/message.txt

    if [ -f usn/usn.json ]; then
      echo -n ' "'$(jq -r .title < usn/usn.json)'"' >> message/message.txt
    fi

    echo -n " ($(date "+%b %e, %Y"))" >> message/message.txt

    echo >> message/message.txt
