---
platform: linux

image_resource:
  type: registry-image
  source: {repository: boshcpi/light-stemcell-builder}

inputs:
- name: builder-src
- name: bosh-stemcells-ci
- name: us-light-stemcell
  optional: true

outputs:
- name: light-stemcell

run:
  path: bosh-stemcells-ci/tasks/light-aws/merge-builds
