---
platform: linux

image_resource:
  type: docker-image
  source: {repository: boshcpi/light-stemcell-builder}

inputs:
  - name: light-stemcell
  - name: bosh-stemcells-ci
  - name: builder-src
  - name: stemcells-index

outputs:
  - name: stemcells-index-output

run:
  path: bosh-stemcells-ci/tasks/light-aws/publish-stemcell-and-checksum.sh

params:
  AWS_ACCESS_KEY_ID:     ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION:    "us-east-1"
  OUTPUT_BUCKET:         ""
