---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bosh/integration, tag: main}
inputs:
- name: builder-src
- name: bosh-stemcells-ci
run:
  path: bosh-stemcells-ci/tasks/light-aws/test-unit.sh
