---
platform: linux

image_resource:
  type: registry-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: bosh-deployment
  - name: bosh-stemcells-ci
  - name: bosh-linux-stemcell-builder
  - name: bosh-cli

outputs:
  - name: director-state

params:


run:
  path: bosh-stemcells-ci/tasks/gcp/deploy-director.sh
